* its structure is hard to maintain. i decided to build a new one

* Hi there!
I am tu10ng.
this is my personal emacs configuration.

* installation
build on vanilla emacs.

you need to download these packages manually to ~/.emacs.d/site-lisp, and follow their readme in order to use:
- [[https://github.com/manateelazycat/lazycat-theme.git][lazycat-theme]]
- [[https://github.com/manateelazycat/awesome-tray.git][awesome-tray]].
- thing-edit
- one-key
- move-text
- duplicate-line
- lsp-bridge
- pyim-tsinghua-dict

you could try the command below:
#+begin_src sh
mkdir -p ~/.emacs.d/site-lisp/
cd ~/.emacs.d/site-lisp/
git clone --depth=1 https://github.com/manateelazycat/lazycat-theme.git
git clone --depth=1 https://github.com/manateelazycat/awesome-tray.git
git clone --depth=1 https://github.com/manateelazycat/thing-edit.git
git clone --depth=1 https://github.com/manateelazycat/one-key.git
git clone --depth=1 https://github.com/manateelazycat/move-text.git
git clone --depth=1 https://github.com/manateelazycat/duplicate-line.git

git clone --depth=1 https://github.com/manateelazycat/lsp-bridge.git
pip3 install epc

git clone --depth=1 https://github.com/redguardtoo/pyim-tsinghua-dict.git
#+end_src

* usage
some daily keybindings:
- M-i `tu10ng/other-window'
- M-u, M-l, M-c will take effect backwards, like (downcase-word (- ARG))
- M-o open new line above
- C-o open new line below
- C-c SPC one-key-menu-thing-edit
- C-s consult search functions
- C-ca org-agenda-list
- C-cc org-capture
- M-. lsp-bridge-jump
- M-<up>, M-<down> move line up/down
- C-M-p, C-M-n duplicate above/below line(changed in source)

* TODO add script to auto download dependencies.
not sure wheter to use git submodule or shell script, or use-package.
